{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}

spec:
  selector:
    app: {{ include "chart.name" . }}
  servers:
  - port:
      number: {{ .Values.service.port }}
      name: http
      protocol: HTTP
    ## I opened this up to any host, but then put a hosts filter on
    # the virtual service below - no idea whether it can be omitted entirely
    # below if not specified (as it probably would be by the template)
    hosts:
    - "*"
##  ToDo:
##    tls:
##      httpsRedirect: true # sends 301 redirect for http requests

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: incoming-traffic-rule
spec:
  ### see note on hosts above - may need an else branch if omitted
  hosts:
  - "*"
  gateways:
  - {{ $fullName }}
  http:
  - match:
    - uri:
        prefix: /saml-idp
    route:
    - destination:
        port:
          number: 7000 # can be omitted if its the only port for reviews
        host: saml-idp.local
{{- end }}
