apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /saml
        backend:
          serviceName: {{ include "chart.fullname" . }}
          servicePort: {{ .Values.service.port }}
---
