{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  
  ### Don't know whether these are important or interesting to the example
  #{{- with .Values.ingress.annotations }}

spec:
  selector:
    app: {{ include "chart.name" . }}
  servers:
  - port:
      number: {{ .Values.service.port }}
      name: http
      protocol: HTTP
    ## I opened this up to any host, but then put a hosts filter on 
    # the virtual service below - no idea whether it can be omitted entirely
    # below if not specified (as it probably would be by the template)
    hosts:
    - "*"
##  ToDo:
##    tls:
##      httpsRedirect: true # sends 301 redirect for http requests

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: incoming-traffic-rule
spec:
  ### see note on hosts above - may need an else branch if omitted
  hosts:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
    {{- end }}  
  gateways:
  - {{ $fullName }}
  - mesh # applies to all the sidecars in the mesh ### not sure if this applies?
  ### remainder of templating left out - here's where we may want to iterate
  # our way back to parameters.  these are left over from the bookinfo
  # sample
  http:
  - match:
    - headers:
        cookie:
          user: dev-123
    route:
    - destination:
        port:
          number: 7777
        host: reviews.qa.svc.cluster.local
  - match:
      uri:
        prefix: /reviews/
    route:
    - destination:
        port:
          number: 9080 # can be omitted if its the only port for reviews
        host: reviews.prod.svc.cluster.local
      weight: 80
    - destination:
        host: reviews.qa.svc.cluster.local
      weight: 20