apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: {{ include "chart.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ include "chart.fullname" . }}
