apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - {{ $fullName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 7000 # can be omitted if its the only port for reviews
        host: {{ $fullName }}
{{- end }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
