{{- $fullName := include "chart.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - book-info-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 7000 # can be omitted if its the only port for reviews
        host: {{ $fullName }}
