# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'saml-idp:$(build.buildId)'
  azureSubscriptionEndpoint: PlayGround Synergi Pipeline (a3a2a87e-1172-4b56-a6fe-8cecb9ae4016)
  dockerId: synergipipeline
  azureContainerRegistry: $(dockerId).azurecr.io

steps:
- task: Docker@1
  displayName: Container registry login
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    command: login
- script: docker build -f Dockerfile -t $(azureContainerRegistry)/$(imageName) .
  displayName: 'docker build'
- script: docker push $(azureContainerRegistry)/$(imageName)
  displayName: 'docker push'
- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'out' 
    publishLocation: 'Container'
